config/routes.rb
PennStationBlog::Engine.routes.draw do
  resources :posts
  resources :categories

  root :to => 'posts#index'
end

app/models/penn_station_blog/category.rb
module PennStationBlog
  class Category < ActiveRecord::Base
    has_and_belongs_to_many :posts, class_name: 'PennStationBlog::Post'

    validates_presence_of :name
    validates_uniqueness_of :name
  end
end

app/models/penn_station_blog/post.rb
module PennStationBlog
  class Post < ActiveRecord::Base
    has_and_belongs_to_many :categories, class_name: 'PennStationBlog::Category'

    validates_presence_of :title
    validates_uniqueness_of :title, :scope => :publication_date

    before_save :make_permalink_title

       # used for admin activities summary

    def name
      title
    end

    def permalink_path()
      "/blog/" + permalink_title
    end

    private

    def make_permalink_title
      date_url = publication_date.to_s.gsub("-", "/")
      self.permalink_title = date_url + "/" + urlize(title)
    end

    # same as for Page
    def urlize(s)
      (s || "").gsub(/ /, "_").gsub(/[^\d\w\-_]/, "").downcase
    end
  end
end

app/controllers/penn_station_blog/application_controller.rb
module PennStationBlog
  class ApplicationController < ::PennStation::ApplicationController
    layout 'layouts/penn_station/application'
  end
end

app/controllers/penn_station_blog/categories_controller.rb
require_dependency "penn_station_blog/application_controller"

module PennStationBlog
  class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @categories = Category.all
    end

    def show
    end

    def new
      @category = Category.new
    end

    def edit
    end

    def create
      @category = Category.new(category_params)

      if @category.save
        redirect_to categories_path, notice: "Successfully created #{@category.name}."
      else
        render action: 'new'
      end
    end

    def update
      if @category.update(category_params)
        redirect_to categories_path
      else
        render action: 'edit'
      end
    end

    def destroy
      @category.destroy
      redirect_to categories_path, notice: "category #{@category.name} was successfully deleted."
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/penn_station_blog/posts_controller.rb
require_dependency "penn_station_blog/application_controller"

module PennStationBlog
  class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]

#    track_admin_activity

    def index
      @posts = Post.all
    end

    def show
    end

    def new
      @post = Post.new
    end

    def edit
    end

    def create
      @post = Post.new(post_params)
      update_categories

      if @post.save
        redirect_to edit_post_path(@post), notice: "Successfully created #{@post.title}."
      else
        render action: 'new'
      end
    end

    def update
      update_categories
      if @post.update(post_params)
        redirect_to posts_path
      else
        render action: 'edit'
      end
    end

    def destroy
      @post.destroy
      redirect_to posts_path, notice: "post #{@post.title} was successfully deleted."
    end

    private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :summary, :body, :publication_date, :publish, :credit)
    end

    def update_categories
      categories = params['post']['category_ids'].reject{|i| i == ""} || []
      @post.categories = categories.map{|c| PennStationBlog::Category.find(c)}.compact
    end
  end
end

app/helpers/penn_station_blog/application_helper.rb
module PennStationBlog
  module ApplicationHelper
  end
end

app/helpers/penn_station_blog/naviation_helper.rb
module PennStationBlog
  module NavigationHelper
    def blog_location(page_type='Blog')
      (p=PennStation::Page.find_by_ptype(page_type)).nil? ? '#' : p.url
    end
  end
end

app/helpers/penn_station_blog/posts_helper.rb
module PennStationBlog
  module PostsHelper
  end
end

app/views/layouts/penn_station_blog/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PennStationBlog</title>
  <%= stylesheet_link_tag    "penn_station_blog/application", media: "all" %>
  <%= javascript_include_tag "penn_station_blog/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/penn_station_blog/categories/_form.html.erb
<%= form_for category do |f| %>
  <% if category.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in category.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions"><%= f.submit 'Save' %></div>

<% end %>

app/views/penn_station_blog/categories/edit.html.erb
<% content_for :toolbar_links do %>
  <ol class="row">
    <li><%= link_to "Back to all categories", categories_path, class: "button delete_button" %></li>
    <li><%= link_to "Delete this category", @category, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
    <li><%= link_to "Back to all posts", posts_path, class: "button delete_button" %></li>
  </ol>
<% end %>

<div id="<%= controller.controller_name %>">
  <h1>Edit <%= @category.name %></h1>
  <%= render(:partial => "penn_station_blog/categories/form", :locals => {:category => @category}) %>
</div>

app/views/penn_station_blog/categories/index.html.erb
<% content_for :toolbar_links do %>
  <ol class="row">
    <li class="category"><a href="<%= new_category_path %>">Add a new category</a></li>
    <li><%= link_to "Back to all posts", posts_path, class: "button delete_button" %></li>
  </ol>
<% end %>

<h1>Manage <%= controller.controller_name %></h1>

<ol id="<%= controller.controller_name %>_index" class="index">
  <li class="title-row row">
    <ol class="cols">
      <li class="name">Name</li>
      <li class="updated_at">Last Updated</li>
    </ol>
  </li>

  <% @categories.each do |category| %>
    <li id="<%= category.id %>" class="row  <%= cycle("even", "odd") -%>">
      <ol class="cols">
        <li class="name"><a href="<%= penn_station_blog.edit_category_path(category) %>"><%= category.name %> <%= image_tag("edit.png") %></a></li>
        <li class="updated_at"><%= formatted_date(category.updated_at) %></li>
      </ol>
    </li>
  <% end %>
</ol>

app/views/penn_station_blog/categories/new.html.erb
<% content_for :toolbar_links do %>
  <ol class="row">
    <li><%= link_to "Back to all categories", categories_path, class: "button delete_button" %></li>
    <li><%= link_to "Back to all posts", posts_path, class: "button delete_button" %></li>
  </ol>
<% end %>

<h1>Create a new category</h1>
<%= render(:partial => "penn_station_blog/categories/form", :locals => {:category => @category}) %>

app/views/penn_station_blog/posts/_form.html.erb
<%= form_for post do |f| %>
  <% if post.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in post.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :credit %>
    <%= f.text_field :credit %>
  </div>

  <div class="field multiline-input">
    <%= f.label :summary %>
    <%= f.text_area :summary %>
  </div>

  <div class="field multiline-input">
    <%= f.label :body %>
    <%= f.text_area :body, :class => "tinymce" %>
  </div>

  <div class="field multiline-input">
    <label>Categories (depress control/command key while clicking to select more than one issue)</label>
    <%= select "post", "category_ids",PennStationBlog::Category.all.collect{|c| [c.name,c.id]},{},{:multiple=>true} %>
  </div>

  <div class="field">
    <%= f.label :publish %>
    <%= f.check_box :publish, {class: 'checkbox'} %>
  </div>

  <div style="margin-bottom: 10px;">
    <label>Publication date</label>
    <%= f.date_select :publication_date %>
  </div>

  <div class="actions"><%= f.submit 'Save' %></div>

<% end %>

app/views/penn_station_blog/posts/edit.html.erb
<% content_for :toolbar_links do %>
  <ol class="row">
    <li><%= link_to "Back to all posts", posts_path, class: "button delete_button" %></li>
    <li><%= link_to "Delete this post", @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "button delete_button" %></li>
  </ol>
<% end %>

<div id="<%= controller.controller_name %>">
  <h1>Edit <%= @post.name %></h1>
  <%= render(:partial => "penn_station_blog/posts/form", :locals => {:post => @post}) %>
</div>

app/views/penn_station_blog/posts/index.html.erb
<% content_for :toolbar_links do %>
  <ol class="row">
    <li class="post"><a href="<%= new_post_path %>">Add a new post</a></li>
    <li class="post"><a href="<%= categories_path %>">Manage blog categories</a></li>
  </ol>
<% end %>

<h1>Manage <%= controller.controller_name %></h1>

<ol id="<%= controller.controller_name %>_index" class="index">
  <li class="title-row row">
    <ol class="cols">
      <li class="title">Title</li>
    </ol>
    <ol class="cols">
      <li class="spacer">&nbsp;</li>
      <li class="published">Published?</li>
      <li class="publication_date">Publication Date</li>
      <li class="blog_categories">Blog Categories</li>
      <li class="allow_comments">Allow Comments?</li>
      <li class="comments">Comments</li>
      <li class="updated_at">Last Updated</li>
    </ol>
  </li>

  <% @posts.each do |post| %>
    <li id="<%= post.id %>" class="row  <%= cycle("even", "odd") -%>">
      <ol class="cols">
        <li class="title">
          <a href="<%= penn_station_blog.edit_post_path(post) %>"><%= post.title %>
            <%= image_tag("edit.png", class: "normal") %>
            <%= image_tag("edit_over.png", class: "hover") %>
          </a>
        </li>
      </ol>
      <ol class="cols">
        <li class="spacer">&nbsp;</li>
        <li class="published"><%= post.publish? ? 'Y' : 'N' %></li>
        <li class="publication_date"><%= post.publication_date %></li>
        <li class="blog_categories">&nbsp;<%#= post.categories.all.map{|c| c.name}.join(", ") %></li>
        <li class="allow_comments">&nbsp;<%#= boolean_checkbox_image(blog_post.allow_comments) %></li>
        <li class="comments">&nbsp;<%#= blog_post.blog_comments.find_all_by_approved(true).size %></li>
        <li class="updated_at"><%= formatted_date(post.updated_at) %></li>
      </ol>
    </li>
  <% end %>
</ol>

app/views/penn_station_blog/posts/new.html.erb
<% content_for :toolbar_links do %>
  <ol class="row">
    <li><%= link_to "Back to all posts", posts_path, class: "button delete_button" %></li>
  </ol>
<% end %>

<h1>Create a new post</h1>
<%= render(:partial => "penn_station_blog/posts/form", :locals => {:post => @post}) %>